### ISSUE TITLE
Token response fields are different than documents

### ISSUE THREAD

**Issue by angeloh** [marinatedpork/oauth_scala#1]
Hi,

https://developers.google.com/identity/protocols/OAuth2WebServer

The token response is different from yours.

access_token <> access (yours)

**Comment by marinatedpork** [comment]
I remember originally thinking "What if they change it to 'accessToken' instead of 'access_token', I'll just find 'access'", but I think that is unlikely I suppose. Same could be done with the 'refresh' in that Token.scala. Nevertheless, I changed the access_token and will likely change the other when I get a chance to revisit it.

I also want to apologize, as this repo is very much in shambles. I was working on this as a side-project, then had to turn my focus elsewhere. At this time, all it really does is Oauth and retrieves a list of files from Drive. I would really encourage you to let me know if you're working toward reading in Drive Sheets or Docs, as I am working toward that eventually.

Thanks checking out the repo!
